//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintControler.MModifyFile.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintControler.MModifyFile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Brim correction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrimCorrection {
            get {
                return ResourceManager.GetString("BrimCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extrude Ratio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrimExtrudeRatio {
            get {
                return ResourceManager.GetString("BrimExtrudeRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enclosure Fan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnclosureFan {
            get {
                return ResourceManager.GetString("EnclosureFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred and {0} could not be changed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCantConvert {
            get {
                return ResourceManager.GetString("MsgCantConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please drop the file you want to print here.
        ///After correcting the file, transfer it. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDropArea {
            get {
                return ResourceManager.GetString("MsgDropArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please correct the error parameter first at first. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgParameterError {
            get {
                return ResourceManager.GetString("MsgParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Offset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OffsetZ {
            get {
                return ResourceManager.GetString("OffsetZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output Parameter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OutputParameter {
            get {
                return ResourceManager.GetString("OutputParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lift Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayRemoval {
            get {
                return ResourceManager.GetString("PlayRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Absolute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectBrimSpeedAbsolute {
            get {
                return ResourceManager.GetString("SelectBrimSpeedAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No change に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectBrimSpeedNoChange {
            get {
                return ResourceManager.GetString("SelectBrimSpeedNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ratio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectBrimSpeedRatio {
            get {
                return ResourceManager.GetString("SelectBrimSpeedRatio", resourceCulture);
            }
        }
    }
}
