//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintControler.MFilamentLoad.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintControler.MFilamentLoad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Filament に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbFilament {
            get {
                return ResourceManager.GetString("LbFilament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbSpeed {
            get {
                return ResourceManager.GetString("LbSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E High に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbSpeedHigh {
            get {
                return ResourceManager.GetString("LbSpeedHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E Low に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbSpeedLow {
            get {
                return ResourceManager.GetString("LbSpeedLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XY Speed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbSpeedXY {
            get {
                return ResourceManager.GetString("LbSpeedXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z Speed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbSpeedZ {
            get {
                return ResourceManager.GetString("LbSpeedZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temp. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbTemp {
            get {
                return ResourceManager.GetString("LbTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbTempHigh {
            get {
                return ResourceManager.GetString("LbTempHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Low に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbTempLow {
            get {
                return ResourceManager.GetString("LbTempLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clean Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PbCleanUp {
            get {
                return ResourceManager.GetString("PbCleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extraction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PbExtraction {
            get {
                return ResourceManager.GetString("PbExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PbInsert {
            get {
                return ResourceManager.GetString("PbInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emergency Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PbStop {
            get {
                return ResourceManager.GetString("PbStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nozzle cleaning pretreatment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rb1Step {
            get {
                return ResourceManager.GetString("Rb1Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filament cut pretreatment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rb2Step {
            get {
                return ResourceManager.GetString("Rb2Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guide tube insertion preprocessing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rb3Step {
            get {
                return ResourceManager.GetString("Rb3Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filament insertion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rb4Step {
            get {
                return ResourceManager.GetString("Rb4Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set to high temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RbTempHigh {
            get {
                return ResourceManager.GetString("RbTempHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set to low temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RbTempLow {
            get {
                return ResourceManager.GetString("RbTempLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The filament is retracted inside the tube. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StCleanupPreProcessStep14 {
            get {
                return ResourceManager.GetString("StCleanupPreProcessStep14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The nozzle is moved up (Z axis stop end). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StCleanupPreProcessStep2 {
            get {
                return ResourceManager.GetString("StCleanupPreProcessStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The nozzle is moved to the right (X axis stop end). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StCleanupPreProcessStep4 {
            get {
                return ResourceManager.GetString("StCleanupPreProcessStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Heated the nozzle and moved to the center. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StCleanupPreProcessStep6 {
            get {
                return ResourceManager.GetString("StCleanupPreProcessStep6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The nozzle is heated and the height is moved to the cleaning position. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StCleanupPreProcessStep8 {
            get {
                return ResourceManager.GetString("StCleanupPreProcessStep8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The nozzle is heated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StExtractionFilamentStep2 {
            get {
                return ResourceManager.GetString("StExtractionFilamentStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove filament. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StExtractionFilamentStep9 {
            get {
                return ResourceManager.GetString("StExtractionFilamentStep9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pulling the filament out of the tube. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StFilamentInExtStep21 {
            get {
                return ResourceManager.GetString("StFilamentInExtStep21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The filament is retracted inside the tube. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StFilamentInExtStep22 {
            get {
                return ResourceManager.GetString("StFilamentInExtStep22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The nozzle is heated and a filament is inserted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StInsertFilamentStep2 {
            get {
                return ResourceManager.GetString("StInsertFilamentStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filaments are extruded from the nozzle.
        ///When the emergency stop button is pushed, stop the extrusion. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StInsertFilamentStep4 {
            get {
                return ResourceManager.GetString("StInsertFilamentStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The nozzle is moved up (Z axis stop end). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StNozzleCleanInsertFilamentStep2 {
            get {
                return ResourceManager.GetString("StNozzleCleanInsertFilamentStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The nozzle is heated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StNozzleCleanInsertFilamentStep4 {
            get {
                return ResourceManager.GetString("StNozzleCleanInsertFilamentStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filaments are extruded from the nozzle.
        ///When the emergency stop button is pushed, stop the extrusion. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StNozzleCleanInsertFilamentStep6 {
            get {
                return ResourceManager.GetString("StNozzleCleanInsertFilamentStep6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filament に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabTitle {
            get {
                return ResourceManager.GetString("TabTitle", resourceCulture);
            }
        }
    }
}
