//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintControler.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintControler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Brim correction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrimCorrection {
            get {
                return ResourceManager.GetString("BrimCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extrude Ratio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrimExtrudeRatio {
            get {
                return ResourceManager.GetString("BrimExtrudeRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnConnect {
            get {
                return ResourceManager.GetString("BtnConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DisConnect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnDisConnect {
            get {
                return ResourceManager.GetString("BtnDisConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnLED {
            get {
                return ResourceManager.GetString("BtnLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stream に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnMovie {
            get {
                return ResourceManager.GetString("BtnMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnStop {
            get {
                return ResourceManager.GetString("BtnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enclosure Fan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnclosureFan {
            get {
                return ResourceManager.GetString("EnclosureFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_Exit {
            get {
                return ResourceManager.GetString("File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_Open {
            get {
                return ResourceManager.GetString("File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbBed {
            get {
                return ResourceManager.GetString("LbBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nozel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbNozel {
            get {
                return ResourceManager.GetString("LbNozel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot connect machine. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCantConnect {
            get {
                return ResourceManager.GetString("MsgCantConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please drop the file you want to print here.
        ///Transfer the dropped file as it is. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDropArea {
            get {
                return ResourceManager.GetString("MsgDropArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Illegal characters or {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgIllegalCaharacter {
            get {
                return ResourceManager.GetString("MsgIllegalCaharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mm/m に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSGMMM {
            get {
                return ResourceManager.GetString("MSGMMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mm/s に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMMS {
            get {
                return ResourceManager.GetString("MsgMMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a value in the range: {1} - {2}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgOutOfRange {
            get {
                return ResourceManager.GetString("MsgOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unconnect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUnConnect {
            get {
                return ResourceManager.GetString("MsgUnConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Offset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OffsetZ {
            get {
                return ResourceManager.GetString("OffsetZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output Parameter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OutputParameter {
            get {
                return ResourceManager.GetString("OutputParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lift Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayRemoval {
            get {
                return ResourceManager.GetString("PlayRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon ProgramIcon {
            get {
                object obj = ResourceManager.GetObject("ProgramIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Absolute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectBrimSpeedAbsolute {
            get {
                return ResourceManager.GetString("SelectBrimSpeedAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No change に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectBrimSpeedNoChange {
            get {
                return ResourceManager.GetString("SelectBrimSpeedNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ratio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectBrimSpeedRatio {
            get {
                return ResourceManager.GetString("SelectBrimSpeedRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetMenu {
            get {
                return ResourceManager.GetString("SetMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabPrint {
            get {
                return ResourceManager.GetString("TabPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adventurer3 Controler に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://{0}:8080/?action=stream に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UriMJepg {
            get {
                return ResourceManager.GetString("UriMJepg", resourceCulture);
            }
        }
    }
}
