//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintControler.MControl.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintControler.MControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add row に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbAddRow {
            get {
                return ResourceManager.GetString("LbAddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbBed {
            get {
                return ResourceManager.GetString("LbBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position X = ????.??? Y = ????.??? Z= ????.??? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbCurrentPosition1 {
            get {
                return ResourceManager.GetString("LbCurrentPosition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position X = {0,8:F3} Y = {1,8:F3} Z= {2,8:F3} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbCurrentPosition2 {
            get {
                return ResourceManager.GetString("LbCurrentPosition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete row に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbDelRow {
            get {
                return ResourceManager.GetString("LbDelRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbE {
            get {
                return ResourceManager.GetString("LbE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop!! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbEmStop {
            get {
                return ResourceManager.GetString("LbEmStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E Spd. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbESpeed {
            get {
                return ResourceManager.GetString("LbESpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbMove {
            get {
                return ResourceManager.GetString("LbMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nozel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbNozel {
            get {
                return ResourceManager.GetString("LbNozel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbPosE {
            get {
                return ResourceManager.GetString("LbPosE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X pos. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbPosX {
            get {
                return ResourceManager.GetString("LbPosX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y pos. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbPosY {
            get {
                return ResourceManager.GetString("LbPosY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z pos. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbPosZ {
            get {
                return ResourceManager.GetString("LbPosZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temp. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbTemp {
            get {
                return ResourceManager.GetString("LbTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbX {
            get {
                return ResourceManager.GetString("LbX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XY Spd. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbXYSpeed {
            get {
                return ResourceManager.GetString("LbXYSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbY {
            get {
                return ResourceManager.GetString("LbY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbZ {
            get {
                return ResourceManager.GetString("LbZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z Spd. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LbZSpeed {
            get {
                return ResourceManager.GetString("LbZSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a value in the range: {1} - {2}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgOutOfRange {
            get {
                return ResourceManager.GetString("MsgOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabTitle {
            get {
                return ResourceManager.GetString("TabTitle", resourceCulture);
            }
        }
    }
}
